apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-1
  namespace: default
  labels:
    app: myapp
  annotations:
    hahah: "test"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1 
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: nginx-www
      mountPath: /etc/nginx/conf.d/
      readOnly: true
  volumes:
  - name: nginx-www
    configMap:
      name: nginx-www
