apiVersion: v1
kind: Pod
metadata:
  name: pod-sa
spec:
  serviceAccountName: myappsa
  containers:
  - name: main
    image:  nginx:1.14
    command:
    - "/bin/bash"
    - "-c"
    - "sleep 10000"
