apiVersion: v1
data:
  wechat.tmpl: |
        {{ define "wechat.default.message" }}
        {{ range .Alerts }}
        告警程序: prometheus_alert
        告警级别: {{ .Labels.severity }}
        告警类型: {{ .Labels.alertname }}
        告警环境: 三元桥测试开发
        故障主机: {{ .Labels.instance }}
        告警主题: {{ .Annotations.summary }}
        告警详情: {{ .Annotations.description }}
        触发时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
        {{ end }}
        {{ end }}
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    chart: prometheus-8.3.0
    component: alertmanager
    heritage: Tiller
    release: prometheus
  name: alertmanager-wechat
  namespace: monitor

