apiVersion: v1
kind: Pod
metadata: 
  name: pod-demo
  namespace: default
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
    - name: myapp
      image: nginx:1.14
    - name: busybox
      image: busybox:latest
      command:
        - "/bin/sh"
        - "-c"
        - "date >> /usr/share/nginx/html/index.html;sleep 3600"
