apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
  namespace: default
spec:
  containers:
    - name: readiness-container
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      lifecycle:
        postStart:
          exec:
              command: ["/bin/sh","-c","mkdir /apps"]
      command: ["/bin/sh","-c","sleep 3600"]
