apiVersion: v1
kind: Service
metadata:
   name: redis
   namespace: default
spec:
  clusterIP: 10.97.97.97
  type: ClusterIP
  selector:
    app: redis
    role: logstor
  ports:
   - port: 6379
     targetPort: 6379
