apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-local
spec:
  storageClassName: manual1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
