apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-true
spec:
  storageClassName: nfs-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/volume
    server: 172.28.61.23
