apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
  labels:
    role: end
spec:
  containers:
  - name: nginx-pod
    image: nginx:1.14
    ports:
      - name: nginx-pod
        containerPort: 80
    volumeMounts:
        - name: nfs
          mountPath: "/usr/share/nginx/html"
        - name: nginxconf
          mountPath: "/etc/nginx/conf.d"
          readOnly: true
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs-true
  - name: nginxconf
    configMap:
      name: nginx-www



