apiVersion: v1
kind: Pod
metadata:
  name: web-1
  namespace: default
  labels:
    role: web-frontend
spec:
  containers:
  - name: web-1
    image: nginx:1.14
    ports:
      - name: web-1
        containerPort: 80
    volumeMounts:
        - name: nfs
          mountPath: "/usr/share/nginx/html"
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
