apiVersion: v1
kind: Pod
metadata:
  name: web-true
  namespace: default
  labels:
    role: frontend
spec:
  containers:
  - name: web-true
    image: nginx:1.14
    ports:
      - name: web
        containerPort: 80
    env:
      - name: NGINX_LISTEN
        valueFrom:
          configMapKeyRef:
            name: web-cm
            key: listen
      - name: NGINX_SERVER_NAME
        valueFrom:
          configMapKeyRef:
            name: web-cm
            key: server_name
    volumeMounts:
        - name: nfs
          mountPath: "/usr/share/nginx/html"
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs-true
