apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  namespace: default
spec:
  replicas: 2
  selector:
     matchLabels:
        app: uuapp
        release: canary
  template:
    metadata:
        labels:
          app: uuapp
          release: canary
    spec:
        containers:
          - name: uuapp-container
            image: nginx:1.14
            ports:
              - name: http
                containerPort: 80  
            env:
               - name: APPLOGLEVEL
                 valueFrom:
                   configMapKeyRef:
                     name: cm-appvars
                     key: apploglevel
               - name: APPDATADIR
                 valueFrom:
                   configMapKeyRef:
                     name: cm-appvars
                     key: appdatadir
