apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test
  namespace: default
spec:
  replicas: 2
  selector:
     matchLabels:
        app: test
        release: canary
  template:
    metadata:
        labels:
          app: test
          release: canary
    spec:
        containers:
          - name: test-container
            image: ikubernetes/myapp:v1
            ports:
              - name: http
                containerPort: 80  
            volumeMounts:
            - name: nginx-www
              mountPath: /etc/nginx/conf.d/
              readOnly: true
        volumes:
        - name: nginx-www
          configMap:
            name: nginx-www
