apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
  namespace: default
  labels:
    app: myapp
    tier: frontend
  annotations:
    magedu.com/created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: nginx:1.14
    ports:
    - name: http
      containerPort: 80
    env:
    - name: NGINX_SERVER_PORT
      valueFrom:
        configMapKeyRef: 
          name: nginx-config
          key: nginx-port
    - name: NGINX_NAME
      valueFrom:
        configMapKeyRef: 
          name: nginx-config
          key: server-name
