apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
     name: pv001
spec:
  nfs:
    path: /data/volumes/v1
    server: stor1.qb.com
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  capacity:
   storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
  labels:
     name: pv002
spec:
  nfs:
    path: /data/volumes/v2
    server: stor1.qb.com
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  capacity:
   storage: 2Gi
