apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  template:
    metadata:
      labels:
        app: fluentd
      name: fluentd
    spec:
      containers:
      - name: fluentd
        image: k8s.gcr.io/google_containers/fluentd-elasticsearch:1.3
        env:
        - name: FLUENTD_ARGS
          value: -qq
        volumeMounts:
        - name: varlog
          mountPath: /varlog
        - name: containers
          mountPath: /var/lib/docker/containers
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: containers
